import { GroupGender, SeedStatus } from "./types";

// ─────────────────────────────────────────────────────────────
// 아이돌 그룹 시드 DB (300+)
// 형식: [displayName, gender, status, koreanName?, fandomName?, aliases?]
//
// - displayName: 글로벌/영문/로마자 표기 (로케일 불변, 번역 금지)
// - status는 Bias Market "내부 시드 분류"일 뿐, 공식 활동 상태 주장이 아님
//   active_candidate / rookie_candidate → 메인 마켓 기본 노출
//   check / legacy_candidate → 필터 선택 시에만 노출
//   hidden → 미노출
// - 기존 라이브 마켓 20팀(BTS 등)은 lib/mockData.ts의 GROUP_SEEDS에 있고
//   여기서 중복되면 자동으로 건너뜀 (슬러그/이름 정규화 dedupe)
// - 새 신인 그룹 추가: 아래에 한 줄 추가하면 끝 (마켓은 자동 생성, 1 Fan$ 출발)
// ─────────────────────────────────────────────────────────────

export type IdolSeedRow = [
  string, // displayName
  GroupGender,
  SeedStatus,
  (string | null)?, // koreanName
  (string | null)?, // fandomName
  string[]? // aliases
];

const A = "active_candidate" as const;
const R = "rookie_candidate" as const;
const L = "legacy_candidate" as const;
const C = "check" as const;

export const IDOL_SEEDS: IdolSeedRow[] = [
  // ── 보이그룹 ──────────────────────────────────────────────
  ["Seo Taiji and Boys", "boy", L, "서태지와 아이들"],
  ["H.O.T.", "boy", L, "에이치오티", null, ["HOT"]],
  ["SECHSKIES", "boy", L, "젝스키스", null, ["젝키"]],
  ["NRG", "boy", L, "엔알지"],
  ["SHINHWA", "boy", L, "신화", "신화창조"],
  ["god", "boy", L, "지오디", null, ["GOD"]],
  ["Buzz", "boy", L, "버즈"],
  ["TVXQ", "boy", C, "동방신기", "Cassiopeia", ["DBSK", "Tohoshinki"]],
  ["SS501", "boy", L, "더블에스오공일", "Triple S"],
  ["SUPER JUNIOR", "boy", C, "슈퍼주니어", "E.L.F.", ["슈주", "SUJU"]],
  ["BIGBANG", "boy", C, "빅뱅", "VIP"],
  ["FTISLAND", "boy", C, "에프티아일랜드", "Primadonna"],
  ["SHINee", "boy", A, "샤이니", "SHINee WORLD", ["샤월"]],
  ["2AM", "boy", L, "투에이엠"],
  ["U-KISS", "boy", C, "유키스", "KISSme"],
  ["2PM", "boy", C, "투피엠", "HOTTEST"],
  ["Highlight", "boy", C, "하이라이트", "LIGHT", ["BEAST", "비스트"]],
  ["CNBLUE", "boy", C, "씨엔블루", "BOICE"],
  ["INFINITE", "boy", C, "인피니트", "INSPIRIT"],
  ["TEEN TOP", "boy", L, "틴탑", "ANGEL"],
  ["Block B", "boy", L, "블락비", "BBC"],
  ["B1A4", "boy", C, "비원에이포", "BANA"],
  ["B.A.P", "boy", L, "비에이피", "BABY", ["BAP"]],
  ["NU'EST", "boy", L, "뉴이스트", "LOVE", ["NUEST"]],
  ["BTOB", "boy", A, "비투비", "Melody"],
  ["VIXX", "boy", C, "빅스", "Starlight"],
  ["GOT7", "boy", C, "갓세븐", "IGOT7", ["아가새"]],
  ["WINNER", "boy", C, "위너", "INNER CIRCLE"],
  ["MONSTA X", "boy", A, "몬스타엑스", "MONBEBE", ["몬엑"]],
  ["N.Flying", "boy", C, "엔플라잉", "N.Fia"],
  ["DAY6", "boy", A, "데이식스", "My Day"],
  ["UP10TION", "boy", L, "업텐션", "HONEY10"],
  ["iKON", "boy", C, "아이콘", "iKONIC"],
  ["ASTRO", "boy", C, "아스트로", "AROHA"],
  ["SNUPER", "boy", L, "스누퍼"],
  ["NCT", "boy", A, "엔시티", "NCTzen", ["NCT 127", "NCT WISH", "엔시티즌"]],
  ["KNK", "boy", L, "크나큰", "Tinkerbell"],
  ["SF9", "boy", C, "에스에프나인", "FANTASY"],
  ["PENTAGON", "boy", C, "펜타곤", "Universe"],
  ["VICTON", "boy", L, "빅톤", "ALICE"],
  ["TST", "boy", L, "티에스티", null, ["탑시크릿"]],
  ["A.C.E", "boy", C, "에이스", "Choice", ["ACE"]],
  ["MYTEEN", "boy", L, "마이틴"],
  ["ONF", "boy", A, "온앤오프", "FUSE"],
  ["Wanna One", "boy", L, "워너원", "Wannable"],
  ["Golden Child", "boy", C, "골든차일드", "Goldenness", ["골차"]],
  ["IZ", "boy", L, "아이즈"],
  ["RAINZ", "boy", L, "레인즈"],
  ["JBJ", "boy", L, "제이비제이", "Joyful"],
  ["IN2IT", "boy", L, "인투잇"],
  ["THE BOYZ", "boy", A, "더보이즈", "THE B", ["더비"]],
  ["TARGET", "boy", L, "타겟"],
  ["W24", "boy", L, "더블유24"],
  ["Spectrum", "boy", L, "스펙트럼"],
  ["D-CRUNCH", "boy", L, "디크런치"],
  ["JBJ95", "boy", L, "제이비제이95"],
  ["Forestella", "boy", C, "포레스텔라"],
  ["M.O.N.T", "boy", C, "몬트", null, ["MONT"]],
  ["VERIVERY", "boy", A, "베리베리", "VERRER"],
  ["ONEUS", "boy", A, "원어스", "TOMOON"],
  ["VANNER", "boy", C, "배너"],
  ["1TEAM", "boy", L, "원팀"],
  ["DKZ", "boy", C, "디케이지", null, ["DONGKIZ", "동키즈"]],
  ["ENOi", "boy", L, "이노이"],
  ["AB6IX", "boy", C, "에이비식스", "ABNEW"],
  ["OnlyOneOf", "boy", C, "온리원오브", "lyOn"],
  ["CIX", "boy", A, "씨아이엑스", "FIX"],
  ["X1", "boy", L, "엑스원", "ONE IT"],
  ["MCND", "boy", C, "엠씨엔디", "GEM"],
  ["TO1", "boy", L, "티오원", null, ["TOO", "티오오"]],
  ["CRAVITY", "boy", A, "크래비티", "LUVITY"],
  ["LA POEM", "boy", C, "라포엠"],
  ["TREASURE", "boy", A, "트레저", "TREASURE MAKER", ["트메"]],
  ["GHOST9", "boy", L, "고스트나인"],
  ["WEi", "boy", C, "위아이", "RUi"],
  ["DRIPPIN", "boy", C, "드리핀", "DREAMIN"],
  ["P1Harmony", "boy", A, "피원하모니", "P1ece", ["피원"]],
  ["BAE173", "boy", C, "비에이이173", "DAY1"],
  ["TFN", "boy", L, "티에프엔", null, ["T1419"]],
  ["The KingDom", "boy", C, "더킹덤"],
  ["MIRAE", "boy", L, "미래소년"],
  ["NTX", "boy", C, "엔티엑스"],
  ["EPEX", "boy", A, "이펙스", "ZENITH"],
  ["OMEGA X", "boy", C, "오메가엑스", "FOR X"],
  ["RE:REVOLUTION", "boy", C, "리레볼루션"],
  ["Xdinary Heroes", "boy", C, "엑스디너리 히어로즈", "Villains", ["엑디즈"]],
  ["TRENDZ", "boy", C, "트렌드지"],
  ["TEMPEST", "boy", C, "템페스트", "iE"],
  ["TAN", "boy", L, "티에이엔"],
  ["NINE.i", "boy", C, "나인아이"],
  ["YOUNITE", "boy", C, "유나이트"],
  ["TNX", "boy", L, "티엔엑스"],
  ["ATBO", "boy", C, "에이티비오"],
  ["PLAVE", "boy", A, "플레이브", "PLLI"],
  ["xikers", "boy", A, "싸이커스", "roadY"],
  ["XODIAC", "boy", C, "소디엑"],
  ["The Wind", "boy", C, "더윈드"],
  ["BOYNEXTDOOR", "boy", A, "보이넥스트도어", "ONEDOOR", ["보넥도"]],
  ["LUN8", "boy", C, "루네이트"],
  ["Hi-Fi Un!corn", "boy", C, "하이파이유니콘", null, ["HiFi Unicorn"]],
  ["ZEROBASEONE", "boy", A, "제로베이스원", "ZEROSE", ["ZB1", "제베원"]],
  ["EVNNE", "boy", A, "이븐", "ENNVE"],
  ["FANTASY BOYS", "boy", C, "판타지보이즈"],
  ["POW", "boy", R, "파우"],
  ["82MAJOR", "boy", R, "에이티투메이저"],
  ["WHIB", "boy", R, "휘브"],
  ["AMPERS&ONE", "boy", R, "앰퍼샌드원"],
  ["ONE PACT", "boy", R, "원팩트"],
  ["TWS", "boy", A, "투어스", "42"],
  ["Big Ocean", "boy", R, "빅오션"],
  ["TIOT", "boy", R, "티아이오티"],
  ["DXMON", "boy", R, "다이몬"],
  ["WATERFIRE", "boy", R, "워터파이어"],
  ["B.D.U", "boy", R, "비디유", null, ["BDU"]],
  ["Galaxy Kids", "boy", R, "갤럭시키즈"],
  ["ARrC", "boy", R, "아크"],
  ["Epic Travelers", "boy", R, "에픽트래블러스"],
  ["XLOV", "boy", R, "엑스러브"],
  ["KickFlip", "boy", R, "킥플립"],
  ["NouerA", "boy", R, "누에라"],
  ["NEWBEAT", "boy", R, "뉴비트"],
  ["CLOSE YOUR EYES", "boy", R, "클로즈유어아이즈", null, ["CYE"]],
  ["AHOF", "boy", R, "에이호프"],
  ["SEVENTOEIGHT", "boy", R, "세븐투에잇"],
  ["CORTIS", "boy", R, "코르티스", "COER"],
  ["NEXZ", "boy", R, "넥스지"],
  ["IDID", "boy", R, "아이디드"],
  ["ALPHA DRIVE ONE", "boy", R, "알파드라이브원"],
  ["YUHZ", "boy", R, "유즈"],
  ["LNGSHOT", "boy", R, "롱샷"],
  ["TUNEXX", "boy", R, "튠엑스"],
  ["KEYVITUP", "boy", R, "키비텁"],
  ["FLARE U", "boy", R, "플레어유"],
  // ── 걸그룹 ──────────────────────────────────────────────
  ["Baby V.O.X", "girl", L, "베이비복스", null, ["Baby VOX"]],
  ["S.E.S.", "girl", L, "에스이에스", null, ["SES"]],
  ["Fin.K.L", "girl", L, "핑클", null, ["FinKL"]],
  ["Brown Eyed Girls", "girl", C, "브라운아이드걸스", null, ["브아걸"]],
  ["Wonder Girls", "girl", L, "원더걸스", "Wonderful"],
  ["KARA", "girl", C, "카라", "Kamilia"],
  ["Girls' Generation", "girl", C, "소녀시대", "SONE", ["SNSD", "소시", "소원"]],
  ["Sunny Hill", "girl", L, "써니힐"],
  ["After School", "girl", L, "애프터스쿨", "PLAYGIRLZ"],
  ["2NE1", "girl", L, "투애니원", "Blackjack"],
  ["4minute", "girl", L, "포미닛", "4NIA"],
  ["T-ARA", "girl", L, "티아라", "QUEEN'S"],
  ["f(x)", "girl", L, "에프엑스", "MeU", ["fx"]],
  ["Rainbow", "girl", L, "레인보우"],
  ["SISTAR", "girl", L, "씨스타", "STAR1"],
  ["Girl's Day", "girl", L, "걸스데이", "Daisy"],
  ["9MUSES", "girl", L, "나인뮤지스", "MINE"],
  ["Apink", "girl", A, "에이핑크", "PANDA"],
  ["EXID", "girl", C, "이엑스아이디", "LEGGO"],
  ["Crayon Pop", "girl", L, "크레용팝"],
  ["AOA", "girl", L, "에이오에이", "Elvis"],
  ["Ladies' Code", "girl", L, "레이디스코드", "Lavely"],
  ["BADKIZ", "girl", L, "배드키즈"],
  ["Berry Good", "girl", L, "베리굿"],
  ["MAMAMOO", "girl", A, "마마무", "MooMoo"],
  ["LABOUM", "girl", L, "라붐", "Lattes"],
  ["Lovelyz", "girl", L, "러블리즈", "Lovelinus"],
  ["SONAMOO", "girl", L, "소나무"],
  ["GFRIEND", "girl", L, "여자친구", "BUDDY", ["여친"]],
  ["CLC", "girl", L, "씨엘씨", "Cheshire"],
  ["OH MY GIRL", "girl", A, "오마이걸", "Miracle", ["옴걸"]],
  ["APRIL", "girl", L, "에이프릴"],
  ["DIA", "girl", L, "다이아", "AID"],
  ["WJSN", "girl", C, "우주소녀", "UJUNG", ["Cosmic Girls", "우정"]],
  ["I.O.I", "girl", L, "아이오아이", null, ["IOI"]],
  ["gugudan", "girl", L, "구구단", "Danjjak"],
  ["MOMOLAND", "girl", L, "모모랜드", "Merry-Go-Round"],
  ["Dreamcatcher", "girl", A, "드림캐쳐", "InSomnia", ["드캐"]],
  ["PRISTIN", "girl", L, "프리스틴", "HIgh"],
  ["Chic Angel", "girl", C, "시크엔젤"],
  ["Girls' Alert", "girl", L, "걸스얼럿"],
  ["ALICE", "girl", C, "앨리스", null, ["ELRIS", "엘리스"]],
  ["G-reyish", "girl", L, "그레이시"],
  ["FAVORITE", "girl", L, "페이버릿"],
  ["Weki Meki", "girl", C, "위키미키", "Ki-Ling"],
  ["S.I.S", "girl", C, "에스아이에스"],
  ["Hash Tag", "girl", L, "해시태그"],
  ["GeeGu", "girl", L, "지구"],
  ["Busters", "girl", C, "버스터즈"],
  ["Girlkind", "girl", L, "걸카인드"],
  ["fromis_9", "girl", A, "프로미스나인", "flover", ["프미"]],
  ["Celeb Five", "girl", C, "셀럽파이브"],
  ["UNI.T", "girl", L, "유니티"],
  ["PRISM", "girl", L, "프리즘"],
  ["SATURDAY", "girl", C, "세러데이"],
  ["NATURE", "girl", L, "네이처"],
  ["LOONA", "girl", L, "이달의 소녀", "Orbit", ["이달소"]],
  ["GWSN", "girl", L, "공원소녀", "Groo"],
  ["Pink Fantasy", "girl", C, "핑크판타지"],
  ["IZ*ONE", "girl", L, "아이즈원", "WIZ*ONE", ["IZONE"]],
  ["K/DA", "girl", L, "케이디에이", null, ["KDA"]],
  ["DreamNote", "girl", L, "드림노트", "Pages"],
  ["Cherry Bullet", "girl", L, "체리블렛", "Lullet"],
  ["EVERGLOW", "girl", C, "에버글로우", "FOREVER"],
  ["Rocket Punch", "girl", C, "로켓펀치", "Ketchy", ["로켓펀치"]],
  ["ANS", "girl", L, "에이엔에스"],
  ["ICU", "girl", L, "아이씨유"],
  ["HINAPIA", "girl", L, "희나피아"],
  ["cignature", "girl", C, "시그니처", "signfan"],
  ["WOOAH", "girl", A, "우아", "wow!", ["woo!ah!"]],
  ["SECRET NUMBER", "girl", C, "시크릿넘버", "LOCK KEY"],
  ["Weeekly", "girl", C, "위클리", "Daileee"],
  ["MAKAMAKA", "girl", L, "마카마카"],
  ["AREAL", "girl", L, "에어리얼"],
  ["Beauty Box", "girl", L, "뷰티박스"],
  ["BLACKSWAN", "girl", C, "블랙스완"],
  ["STAYC", "girl", A, "스테이씨", "SWITH"],
  ["TRI.BE", "girl", C, "트라이비", "TRUE"],
  ["PIXY", "girl", C, "픽시"],
  ["PURPLE KISS", "girl", A, "퍼플키스", "PLORY", ["퍼키"]],
  ["HOT ISSUE", "girl", L, "핫이슈"],
  ["LIGHTSUM", "girl", A, "라잇썸", "SUMIT"],
  ["Hi-L", "girl", L, "하이엘"],
  ["PRITTI-G", "girl", L, "프리티지"],
  ["ICHILLIN'", "girl", C, "아이칠린", null, ["ICHILLIN"]],
  ["Billlie", "girl", A, "빌리", "Belllie've"],
  ["SKYLE", "girl", C, "스카이레"],
  ["Kep1er", "girl", A, "케플러", "Kep1ian", ["케원"]],
  ["H1-KEY", "girl", A, "하이키", "M1-KEY"],
  ["VIVIZ", "girl", A, "비비지", "Na.V"],
  ["CLASS:y", "girl", L, "클라씨", "CLIKE:y", ["CLASSy"]],
  ["Lapillus", "girl", C, "라필루스", "Lapis"],
  ["Girls' World", "girl", L, "소녀세계"],
  ["CSR", "girl", C, "첫사랑", "Maehwa"],
  ["MIMIIROSE", "girl", C, "미미로즈"],
  ["PRIMROSE", "girl", C, "프림로즈"],
  ["Free In Sass", "girl", C, "프리인사스"],
  ["tripleS", "girl", A, "트리플에스", "WAV", ["트리플S"]],
  ["X:IN", "girl", C, "엑신", null, ["XIN"]],
  ["KISS OF LIFE", "girl", A, "키스오브라이프", "KISSY", ["키오프"]],
  ["BBGIRLS", "girl", C, "브브걸", null, ["Brave Girls", "브레이브걸스"]],
  ["EL7Z UP", "girl", L, "엘즈업"],
  ["Loossemble", "girl", C, "루셈블"],
  ["QWER", "girl", A, "큐더블유이알", "Bawi Ge", ["바위게"]],
  ["YOUNG POSSE", "girl", R, "영파씨"],
  ["eite", "girl", R, "에이트"],
  ["Geenius", "girl", R, "지니어스"],
  ["ILLIT", "girl", A, "아일릿", "GLLIT"],
  ["RESCENE", "girl", R, "리센느", "REMINE"],
  ["Candy Shop", "girl", R, "캔디샵"],
  ["UNIS", "girl", A, "유니스", "EverAfter"],
  ["VVUP", "girl", R, "비비업"],
  ["BEWAVE", "girl", R, "비웨이브"],
  ["ARTMS", "girl", A, "아르테미스", "OURII"],
  ["BADVILLAIN", "girl", R, "배드빌런", "VILLAIN-ON"],
  ["MADEIN", "girl", R, "메이딘", "MABY"],
  ["MEOVV", "girl", R, "미야오", "PAWMPAWM"],
  ["FIFTY FIFTY", "girl", A, "피프티 피프티", "TWENY", ["5050"]],
  ["izna", "girl", R, "이즈나", "naya"],
  ["HONEYZ", "girl", R, "허니즈"],
  ["SAY MY NAME", "girl", R, "세이마이네임", "LOVvmE"],
  ["ODD YOUTH", "girl", R, "오드유스", "ODYz"],
  ["LOVEONE", "girl", R, "러브원", "LOVEWITH"],
  ["ANGEL NOISE", "girl", R, "엔젤노이즈"],
  ["Hearts2Hearts", "girl", R, "하츠투하츠", "S2U", ["하투하"]],
  ["KiiiKiii", "girl", R, "키키", "TiiiKiii"],
  ["ifeye", "girl", R, "이프아이"],
  ["HITGS", "girl", R, "히츠"],
  ["ablume", "girl", R, "에이블룸"],
  ["KIIRAS", "girl", R, "키라스", "KIIVELY"],
  ["Baby DONT Cry", "girl", R, "베이비돈크라이", "Cherries", ["BDC"]],
  ["CrazAngel", "girl", R, "크레이즈엔젤"],
  ["AtHeart", "girl", R, "앳하트", "heartbeat"],
  ["iii", "girl", R, "아이아이아이"],
  ["ACAXIA", "girl", R, "아카시아"],
  ["OWIS", "girl", R, "오위스"],
  ["UNCHILD", "girl", R, "언차일드"],
  ["H//PE Princess", "girl", R, "호프프린세스", null, ["HPE Princess"]],
  // ── 최신/기타 ────────────────────────────────────────────
  ["AxMxP", "boy", R, "에이엠피"],
  ["AllDay Project", "coed", R, "올데이프로젝트", null, ["ADP"]],
  ["1Verse", "boy", R, "원버스"],
  ["3way", "girl", R, "쓰리웨이"],
  ["Am8ic", "boy", R, "앰빅"],
  ["Be Boys", "boy", R, "비보이즈"],
  ["Blockxy", "girl", R, "블록시"],
  ["OFF EQUALS", "boy", R, "오프이퀄스"],
  ["IXIA", "girl", R, "익시아"],
  ["idntt", "boy", R, "아이든트"],
  ["N.TOP", "boy", R, "엔탑"],
  ["TDYA", "boy", R, "티디야"],
  ["Backstage Boys", "boy", R, "백스테이지보이즈"],
  ["DNA", "boy", R, "디엔에이"],
  ["PLAYNA", "girl", R, "플레이나"],
  ["TIMT", "boy", R, "팀트"],
  ["PTMRS", "girl", R, "피트모스"],
  ["Skinz", "boy", R, "스킨즈"],
  ["Smorz", "boy", R, "스모어즈"],
  ["Sweet:ch", "girl", R, "스위치"],
  ["UAU", "girl", R, "유에이유"],
  ["UDTT", "boy", R, "유디티티"],
  ["Uspeer", "boy", R, "유스피어"],
  ["ZooniZini", "girl", R, "주니지니"],
  ["VVS", "boy", R, "브이브이에스"],
  ["HIGHSSO", "girl", R, "하이쏘"],
  ["HONEY POPCORN", "girl", L, "허니팝콘"],
  ["CRAXY", "girl", C, "크랙시"],
  ["CHECKMATE", "coed", C, "체크메이트"],
];
